// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ueaamJQPez7AwMHobw3iwx
// Component: kRzcWJyrXSTmv
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_sanitize.module.css"; // plasmic-import: ueaamJQPez7AwMHobw3iwx/projectcss
import sty from "./PlasmicForwardButton.module.css"; // plasmic-import: kRzcWJyrXSTmv/css

import forwardIconpngPlvgPlqE3V7Jk from "./images/forwardIconpng.png"; // plasmic-import: PLVGPlqE3V7jk/picture

export type PlasmicForwardButton__VariantMembers = {};
export type PlasmicForwardButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicForwardButton__VariantsArgs;
export const PlasmicForwardButton__VariantProps = new Array<VariantPropType>();

export type PlasmicForwardButton__ArgsType = {};
type ArgPropType = keyof PlasmicForwardButton__ArgsType;
export const PlasmicForwardButton__ArgProps = new Array<ArgPropType>();

export type PlasmicForwardButton__OverridesType = {
  forwardButton?: p.Flex<"div">;
  img?: p.Flex<"img">;
};

export interface DefaultForwardButtonProps {
  className?: string;
}

function PlasmicForwardButton__RenderFunc(props: {
  variants: PlasmicForwardButton__VariantsArgs;
  args: PlasmicForwardButton__ArgsType;
  overrides: PlasmicForwardButton__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"forwardButton"}
      data-plasmic-override={overrides.forwardButton}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.root_reset,
        sty.forwardButton
      )}
    >
      <img
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(defaultcss.img, sty.img)}
        role={"img"}
        src={forwardIconpngPlvgPlqE3V7Jk}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  forwardButton: ["forwardButton", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  forwardButton: "div";
  img: "img";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicForwardButton__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicForwardButton__VariantsArgs;
    args?: PlasmicForwardButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicForwardButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicForwardButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicForwardButton__ArgProps,
      internalVariantPropNames: PlasmicForwardButton__VariantProps
    });

    return PlasmicForwardButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "forwardButton") {
    func.displayName = "PlasmicForwardButton";
  } else {
    func.displayName = `PlasmicForwardButton.${nodeName}`;
  }
  return func;
}

export const PlasmicForwardButton = Object.assign(
  // Top-level PlasmicForwardButton renders the root element
  makeNodeComponent("forwardButton"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicForwardButton
    internalVariantProps: PlasmicForwardButton__VariantProps,
    internalArgProps: PlasmicForwardButton__ArgProps
  }
);

export default PlasmicForwardButton;
/* prettier-ignore-end */
